[project]
name = "oasis-task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ttanvirr", email = "tanvir.artisan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "psycopg[binary,pool]>=3.3.4",
]

[project.scripts]
oasis-task-manager = "oasis_task_manager:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
